name: 'teams webhook action'
description: 'teams webhook action unit'
author: 'saito'
inputs:
  who-to-greet:  # id of input
    description: 'who to greet'
    required: true
    default: 'World' 
outputs:
  time: # id of output
    description: 'The time we greeted you'
branding:
  icon: 'link'
  color: 'red'
runs:
  using: 'node12'
  main: 'index.js'
