name: 'teams webhook action'
description: 'teams webhook action unit'
author: 'saito'
inputs:
  ami:
    required: true
    default: 'World'
branding:
  icon: 'link'
  color: 'red'
runs:
  using: 'node12'
  main: 'index.js'
